### ISSUE TITLE
node crash error

### ISSUE THREAD

**Issue by hail100** [ritual-net/infernet-node#12] opened 2024-03-01 06:26 UTC
docker image   ritualnetwork/infernet-node:0.1.0
```
2024-03-01 06:21:40 [info     ] Serving REST webserver                             [server.rest] addr=0.0.0.0 port=2631
/usr/local/lib/python3.11/site-packages/structlog/stdlib.py:1062: UserWarning: Remove `format_exc_info` from your processor chain if you want pretty exceptions.
  ed = p(logger, meth_name, ed)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/logging/__init__.py", line 1110, in emit
    msg = self.format(record)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/logging/__init__.py", line 953, in format
    return fmt.format(record)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/structlog/stdlib.py", line 1062, in format
    ed = p(logger, meth_name, ed)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/structlog/dev.py", line 513, in __call__
    sio.write("\n" + exc)
              ~~~~~^~~~~
TypeError: can only concatenate str (not "ValueError") to str
Call stack:
  File "/app/src/main.py", line 183, in <module>
    lifecycle_main()
  File "/app/src/main.py", line 176, in lifecycle_main
    loop.run_until_complete(lifecycle_run())
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 640, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1922, in _run_once
    handle._run()
  File "/usr/local/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/app/src/main.py", line 125, in lifecycle_run
    log.error("Task exception", exception=task.exception())
  File "/usr/local/lib/python3.11/site-packages/structlog/stdlib.py", line 200, in error
    return self._proxy_to_logger("error", event, *args, **kw)
  File "/usr/local/lib/python3.11/site-packages/structlog/stdlib.py", line 247, in _proxy_to_logger
    return super()._proxy_to_logger(method_name, event=event, **event_kw)
  File "/usr/local/lib/python3.11/site-packages/structlog/_base.py", line 223, in _proxy_to_logger
    return getattr(self._logger, method_name)(*args, **kw)
Message: {'exception': ValueError({'code': -32000, 'message': 'filter not found'}), 'event': 'Task exception', 'level': 'error', 'logger': '__main__', 'timestamp': '2024-03-01 06:21:40'}
Arguments: ()
2024-03-01 06:21:40 [info     ] Exited main process                                [__main__] 
```

**Comment by stelios-ritual** [comment] 2024-03-01 23:25
Closing as a duplicate of #7. Please re-open if different url doesn't fix it. You can always seek help in our [Discord server](https://discord.gg/ritual-net)

**Closed by stelios-ritual** 2024-03-01 23:25 UTC
