### ISSUE TITLE
Container stuck in restart loop

### ISSUE THREAD

**Issue by meta-light** [ritual-net/infernet-node#1] opened 2024-01-19 15:15 UTC
Ever 3 seconds or so my deploy-node-1 container is restarting, unsure how to troubleshoot

**Comment by samboluy** [comment] 2024-01-26 20:57
Hi team, I face the same issue as Meta-light, my container ( ritualnetwork/infernet-node:0.1.0 ) deploy-node-1 is restarting every few second, it won't stay online, I tried restart and rerun to no success.

**Comment by srvinii** [comment] 2024-01-29 22:20
I suggest taking a look at the container logs with `docker logs -f anvil-node` and sharing more details

**Comment by stelios-ritual** [comment] 2024-01-30 18:37
Happy to help troubleshoot if you show me a tail of your node logs!

**Comment by hacchi999** [comment] 2024-02-05 02:39
KeyError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/src/main.py", line 182, in <module>
    on_startup()
  File "/app/src/main.py", line 38, in on_startup
    config: ConfigDict = load_validated_config()
                         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/utils/config.py", line 162, in load_validated_config
    validate_config(config)
  File "/app/src/utils/config.py", line 147, in validate_config
    raise Exception(f"Missing config param: {item.key_path}")
Exception: Missing config param: chain.rpc_url
Traceback (most recent call last):
  File "/app/src/utils/config.py", line 145, in validate_config
    validate(config, path, item.expected_type, item.optional)
  File "/app/src/utils/config.py", line 118, in validate
    validate(config[next_key], path, expected_type, optional)
  File "/app/src/utils/config.py", line 127, in validate
    raise KeyError

What is causing this to reboot loop?

**Comment by stelios-ritual** [comment] 2024-02-05 16:40
Your `config.json` is malformed, specifically `chain.rpc_url` is not defined.

Even if you set `chain.enabled` to `false`, `rpc_url` should still exist as a key, even though it's not used. You can set it to `""`.

**Comment by hacchi999** [comment] 2024-02-06 02:04
I may be making a big mistake.

1. do I need to install InfernetSDK first to start up infernet-node and register the node?

2. I modified the config.json with the rpc_url entry as per your answer.
　chain: {
    "enabled": false,
    "trail_head_blocks": 5,
    "rpc_ws": "http://127.0.0.1:8545",
    "rpc_url": "",
    "coordinator_address": "0x..." ,
    "wallet": {
      "max_gas_limit": 5000000,
      "private_key": "0x..."
    }
  }, }

I'm going to start this up and rename the container to register the node.　
　I ran docker exec container-name make register-node.

Traceback (most recent call last):
  File "/app/scripts/register_node.py", line 60, in <module
    loop.run_until_complete(register_node())
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/app/scripts/register_node.py", line 33, in register_node
    rpc = RPC(config["chain"]["rpc_url"])
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/chain/rpc.py", line 93, in __init__
    raise ValueError("Incorrect RPC URL format")
ValueError: Incorrect RPC URL format
make: *** [Makefile:42: register-node] Error 1

It seems that rpc_url is the cause again.

　If I enter rpc_url, which value?
　Also coordinator_address and private_key enter my test wallet?

I just can't get it to work. Please forgive my clumsiness.

**Comment by stelios-ritual** [comment] 2024-02-06 02:13
Oh I see, apologies for that. See issue https://github.com/ritual-net/infernet-node/issues/4. rpc_ws is an error in the sample config.

**Comment by hacchi999** [comment] 2024-02-06 03:02
Thanks for your politeness.

The next time I proceed to register a node, I get this error

ClientConnectorError: Cannot connect to host 127.0.0.1:8545 ssl:default [Connect call failed ('127.0.0.1', 8545)].

**Comment by arshan-ritual** [comment] 2024-02-06 14:28
> ClientConnectorError: Cannot connect to host 127.0.0.1:8545 ssl:default [Connect call failed ('127.0.0.1', 8545)].
if you have chain disabled in your config, then that shouldn't really show as the infernet node shouldn't attempt to connect to the chain. I am quite confused why that is happening. 

Refer to the [config](https://github.com/ritual-net/infernet-container-starter/blob/main/projects/hello-world/container/config.json) file in our hello-world example for reference. If you enable the chain, and decide to run a local anvil node, that config file contains both the correct `rpc_url` as well as the [anvil-node](https://github.com/ritual-net/infernet-container-starter/blob/main/projects/hello-world/container/config.json#L39) that's listed under its containers.

**Comment by alchemykrat** [comment] 2024-02-22 06:26
> Hello @hacchi999, registering a node with the infernet coordinator is a bit involved as there's a cooldown period. Here's an example of how someone registered their contract with the infernet coordinator. You first have to [register](https://basescan.org/tx/0x02d033d179aa80477f66202b451d42aff9beaae1d567ebc24071bb189cb72c05) your node, then after a cooldown period of an hour, you'll be able to [activate](https://basescan.org/tx/0xdab9e28e3f529d93925d9ac6ba33131bfad32bc49308b6739dc66beff73894c3) your node.
> 
> To run things locally, for convenience we have an [infernet-anvil-testnet](https://github.com/ritual-net/infernet-container-starter?tab=readme-ov-file#infernets-anvil-testnet) docker image deployed that has a coordinator deployed, with a node address that has already been registered. I suggest using the private key for that node for your local development. I also suggest going through our [hello-world](https://github.com/ritual-net/infernet-container-starter?tab=readme-ov-file#getting-started) example to understand how things work end-to-end.

Registering the node is manual with base contract?

**Comment by alchemykrat** [comment] 2024-02-22 06:28
It's restarting in every 4 secs

CONTAINER ID   IMAGE                               COMMAND                  CREATED          STATUS                         PORTS                                NAMES
3bbba109bc79   ritualnetwork/infernet-node:0.1.0   "/app/entrypoint.sh"     7 minutes ago    Restarting (1) 7 seconds ago                                        deploy-node-1
17c15aa59536   redis:latest                        "docker-entrypoint.s…"   10 minutes ago   Up 7 minutes                   0.0.0.0:6379->6379/tcp               deploy-redis-1
b8038eb31bb9   fluent/fluent-bit:latest            "/fluent-bit/bin/flu…"   10 minutes ago   Up 7 minutes                   2020/tcp, 0.0.0.0:24224->24224/tcp   deploy-fluentbit-1

**Comment by stelios-ritual** [comment] 2024-03-01 23:20
Closing this issue given that we now have a [Discord server](url) where community and team members can help you troubleshoot.

**Closed by stelios-ritual** 2024-03-01 23:20 UTC
